---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app: prometheus
    role: server
spec:
  type: ClusterIP
  ports:
    - port: 32321
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
    role: server