---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
spec:
  type: ClusterIP
  ports:
    - port: 32322
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
    role: core