# elasticsearch-data.configmap.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: elasticsearch-data-config
  labels:
    app: elasticsearch
    role: data
data:
  elasticsearch.yml: |-
    cluster.name: ${CLUSTER_NAME}
    node.name: ${NODE_NAME}
    discovery.seed_hosts: ${NODE_LIST}
    cluster.initial_master_nodes: ${MASTER_NODES}

    network.host: 0.0.0.0

    node:
      master: false
      data: true
      ingest: false

    reindex.remote.whitelist: "esingest.com.br:9200, 10.10.4.*:9200, ip-10-10-4-114.ec2.internal:9200"
    thread_pool.snapshot.max: 8
    xpack.security.enabled: true
    xpack.monitoring.collection.enabled: true
    search.remote.connect: false